from django.urls import path
from . import views
from .views import *

urlpatterns = [
    path('', views.home, name='school-home'),
    path('profile/', views.profile, name='school-profile'),
    path('teachers/', views.teachers, name='school-teachers'),
    path('resources/', views.resources, name='school-resources'),
    path('profile/set/', SetProfileCreateView.as_view(), name='set-school-profile'),
    path('profile/add/', SchoolCreateView.as_view(), name='add-school-profile'),
    path('teachers/add/', SchoolTeacherCreateView.as_view(), name='add-school-teacher'),
    path('teachers/register/', TeacherCreateView.as_view(), name='register-teacher'),
    path('teachers/view/', SchoolTeacherListView.as_view(), name='view-school-teachers'),
    path('profiles/<int:pk>/update/', SchoolProfileUpdateView.as_view(), name='update-school-profile'),
    path('teachers/<int:pk>/update/', SchoolTeacherUpdateView.as_view(), name='update-school-teacher'),
    path('teachers/<int:pk>/', SchoolTeacherDetailView.as_view(), name='school-teacher-details'),
    path('resources/add/', SchoolResourceCreateView.as_view(), name='add-school-resource'),
    path('resources/<int:pk>/update/', SchoolResourceUpdateView.as_view(), name='update-school-resource'),
    path('resources/view/', SchoolResourceListView.as_view(), name='view-school-resources'),
    path('resources/<int:pk>/', SchoolResourceDetailView.as_view(), name='school-resource-details'),
    path('students/', views.students, name='students'),
    path('students/enrollments/add', views.students, name='add-students'),
    path('students/repeaters/add', views.add_repeaters, name='add-repeaters'),
    path('students/repeaters/', views.view_repeaters, name='view-repeaters'),
    path('students/nationality/add', views.add_nationality, name='add-nationality'),
    path('students/nationality/', views.view_nationality, name='view-nationality'),
    path('students/physical_streams/', views.add_physical_streams, name='add-physical-streams'),
    path('students/physical_streams/', views.view_physical_streams, name='view-physical-streams'),
    path('students/orphans/', views.add_orphans, name='add-orphans'),
    path('students/orphans/', views.view_orphans, name='view-orphans'),
    path('students/special_needs/', views.add_special_needs, name='add-special-needs'),
    path('students/special_needs/', views.view_special_needs, name='view-special-needs'),
    path('students/seating_and_writing_space/', views.add_seating_and_writing_space, name='add-seating-and-writing-space'),
    path('students/seating_and_writing_space/', views.view_seating_and_writing_space, name='view-seating-and-writing-space'),
    path('students/transfered_students/', views.add_transfered_students, name='add-transfered-students'),
    path('students/transfered_students/', views.view_transfered_students, name='view-transfered-students'),
    path('students/examinations/', views.add_examinations, name='add-examinations'),
    path('students/examinations/', views.view_examinations, name='view-examinations'),
    path('students/proposed_intake/', views.add_proposed_intake, name='add-proposed-intake'),
    path('students/proposed_intake/', views.view_proposed_intake, name='view-proposed-intake'),
    path('students/new_entrants/', views.add_new_entrants, name='add-new-entrants'),
    path('students/new_entrants/', views.view_new_entrants, name='view-new-entrants'),
    path('students/<int:pk>/update/', StudentUpdateView.as_view(), name='update-student'),
    path('students/enrolments/', views.students, name='view-students'),
    path('teachers/remain/add/', views.add_left_teachers, name='add-left-teachers'),
    path('teachers/nonteaching/add', views.add_non_teaching_staff, name='add-non-teaching-staff'),
    path('teachers/allocation/', views.teacher_allocation, name='teacher-allocation'),
    path('resources/buildings/add/', views.add_buildings, name='add-buildings'),
    path('resources/buildings/construction/add', views.add_buildings_under_construction, name='add-buildings-under-construction'),
    path('resources/buidings/needed/', views.add_rooms_needed, name='add-buildings-needed'),
    path('resources/latrines/add/', views.add_latrines, name='add-latrines'),
    path('resources/water/energy/add', views.add_water_and_energy_sources, name='add-water-and-energy-sources'),
    path('teachers/request/', RequestTeacherCreateView.as_view(), name='request-teacher'),
    path('teachers/requests/<int:pk>/update/', RequestTeacherUpdateView.as_view(), name='update-teacher-request'),
    path('teachers/requests/view/', RequestTeacherListView.as_view(), name='teacher-requests'),
]
